services:
  app:
    build: .
    container_name: bucket_browser
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONPATH=/usr/src/app
    env_file:
      - .env
